# Generated by Django 5.2 on 2025-04-20 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleID', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
                ('votePermission', models.BooleanField(default=False)),
                ('viewTeamSummary', models.BooleanField(default=False)),
                ('viewDepartmentSummary', models.BooleanField(default=False)),
                ('ManageTeamPermission', models.BooleanField(default=False)),
                ('viewProgressPermission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('teamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.team')),
            ],
        ),
    ]
