# Generated by Django 5.2 on 2025-04-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='ManageTeamPermission',
            new_name='manageTeamPermission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
