# Generated by Django 5.0 on 2025-04-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_manageteampermission_role_manageteampermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentNo', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='role',
            old_name='manageTeamPermission',
            new_name='manageTeamsPermission',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='userID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roleId',
        ),
        migrations.AddField(
            model_name='role',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=20, unique=True)),
                ('departmentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='teamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team'),
        ),
    ]
