# Generated by Django 5.2 on 2025-04-20 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('cardName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentNo', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateID', models.AutoField(primary_key=True, serialize=False)),
                ('stateColour', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamID', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('trendID', models.AutoField(primary_key=True, serialize=False)),
                ('trendStatus', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteID', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('summary', models.TextField(verbose_name=200)),
                ('progress', models.TextField(verbose_name=200)),
                ('departmentNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.department')),
            ],
        ),
    ]
