# Generated by Django 5.2 on 2025-04-20 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='departmentNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.department'),
        ),
        migrations.AddField(
            model_name='session',
            name='teamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.team'),
        ),
        migrations.AddField(
            model_name='vote',
            name='sessionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.session'),
        ),
        migrations.AddField(
            model_name='vote',
            name='stateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.state'),
        ),
        migrations.AddField(
            model_name='vote',
            name='trendID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.trend'),
        ),
    ]
