# Generated by Django 5.2 on 2025-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='progress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='summary',
            field=models.TextField(),
        ),
    ]
