# Generated by Django 5.2 on 2025-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_session_progress_alter_session_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
